P3AddNewFunctionalityDotNetCore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using P3AddNewFunctionalityDotNetCore.Models;

namespace P3AddNewFunctionalityDotNetCore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;

        public CartSummaryViewComponent(ICart cart)
        {
            _cart = cart as Cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

P3AddNewFunctionalityDotNetCore/Components/LanguageSelectorViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using P3AddNewFunctionalityDotNetCore.Models.Services;

namespace P3AddNewFunctionalityDotNetCore.Components
{
    public class LanguageSelectorViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(ILanguageService languageService)
        {
            return View(languageService);
        }
    }
}

P3AddNewFunctionalityDotNetCore/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Mvc;
using P3AddNewFunctionalityDotNetCore.Models.Services;
using P3AddNewFunctionalityDotNetCore.Models.ViewModels;

namespace P3AddNewFunctionalityDotNetCore.Controllers
{
    public class LanguageController : Controller
    {
        private readonly ILanguageService _languageService;

        public LanguageController(ILanguageService languageService)
        {
            _languageService = languageService;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ChangeUiLanguage(LanguageViewModel model, string returnUrl)
        {
            if (model.Language != null)
            {
                _languageService.ChangeUiLanguage(HttpContext, model.Language);
            }

            return Redirect(returnUrl);
        }
    }
}

P3AddNewFunctionalityDotNetCore/Views/Shared/Components/LanguageSelector/Default.cshtml
@model P3AddNewFunctionalityDotNetCore.Models.ViewModels.LanguageViewModel

<form asp-action="ChangeUiLanguage" asp-controller="Language" method="post">
    <div class="form-group">
        <label class="col-md-3 control-label" style="float:left">@Localizer["Language"]</label>
        <div class="col-md-7" style="float:left">
            <select asp-for="Language">
                <option disabled selected style="font-style:italic">@Localizer["ChangeLanguage"]</option>
                <option value="English">@Localizer["LanguageEnglish"]</option>
                <option value="French">@Localizer["LanguageFrench"]</option>
                @*<option value="Spanish">@Localizer["LanguageSpanish"]</option>*@
            </select>
        </div>
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.Path" />
        <button class="col-md-2" type="submit" style="float:left"> OK </button>
    </div>
</form>